### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by kovirolik** [OctoNezd/ShararamTAS#1]
> Traceback (most recent call last):
>   File "main.py", line 11, in <module>
>     x, y = pyautogui.locateCenterOnScreen('Searchbar.PNG')
> TypeError: 'NoneType' object is not iterable

**Comment by evgfilim1** [comment]
@kovirolik Can you describe, what did you do before and how did you get this error

**Comment by OctoNezd** [comment]
@kovirolik Работает только на Firefox

**Comment by OctoNezd** [comment]
@OctoNezd и с английским языком

**Comment by OlexiyUA** [comment]
@OctoNezd Lol

**Comment by kovirolik** [comment]
http://imgur.com/Qg2q3vbl.png

**Comment by kovirolik** [comment]
Может шрифт?

**Comment by OctoNezd** [comment]
@kovirolik Возможно, точно не знаю

**Comment by kovirolik** [comment]
@OctoNezd заменил пикчу , а оно не работает((9 зараза

**Comment by kovirolik** [comment]
![alt text](http://i.imgur.com/jbJgGTD.png "лол кек чебурек")
хмм....

**Comment by kovirolik** [comment]
@evgfilim1 как и всегда

**Comment by evgfilim1** [comment]
@kovirolik что "как и всегда"?

**Comment by kovirolik** [comment]
@evgfilim1 запускаю фирефакс , python main.py и ошибка

**Comment by kovirolik** [comment]
все пофиксил

**Comment by kovirolik** [comment]
ща форк сделаю

**Comment by kovirolik** [comment]
@OctoNezd закрывай!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**1!!!!!!!!**_!1!!!!!!_
